// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:accountCircle': typeof import('~icons/mdi/account-circle')['default']
    'IconMdi:accountMultipleCheck': typeof import('~icons/mdi/account-multiple-check')['default']
    'IconMdi:accountMultipleOutline': typeof import('~icons/mdi/account-multiple-outline')['default']
    'IconMdi:bookOpenVariant': typeof import('~icons/mdi/book-open-variant')['default']
    'IconMdi:briefcaseAccount': typeof import('~icons/mdi/briefcase-account')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:codeTags': typeof import('~icons/mdi/code-tags')['default']
    'IconMdi:fileDocumentEditOutline': typeof import('~icons/mdi/file-document-edit-outline')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:group': typeof import('~icons/mdi/group')['default']
    'IconMdi:lightbulbOutline': typeof import('~icons/mdi/lightbulb-outline')['default']
    'IconMdi:school': typeof import('~icons/mdi/school')['default']
    'IconMdi:timeline': typeof import('~icons/mdi/timeline')['default']
    'IconMdi:update': typeof import('~icons/mdi/update')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
